name: ci-v4

on:
  push:
    branches:
      - main
      - develop
    tags-ignore:
      - '*'
    paths-ignore:
      - LICENSE
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '6.0.x'

    - name: Build & test # 1. Run multiple commands
      run: |
        echo ${{ env.GITHUB_ACTION_REPOSITORY }} # https://docs.github.com/en/actions/learn-github-actions/environment-variables
        ls -la
        dotnet test ./src/Crypto.sln --configuration Release
        
        
