name: ci-v0 # https://docs.github.com/en/actions

on: # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
  push:
    branches: [ main ]
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Build & test
      run: |
        dotnet test ./src/Crypto.sln --configuration Release  -- xunit.parallelizeAssembly=true