name: ci-v5

on:
  push:
    branches:
      - main
      - develop
    tags-ignore:
      - '*'
    paths-ignore:
      - LICENSE
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }} # 1. Run on multiple operating systems

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/PackSite.Library.Crypto.sln

    - name: Build
      run: dotnet build ./src/PackSite.Library.Crypto.sln --no-restore

    - name: Test
      run: dotnet test ./src/PackSite.Library.Crypto.sln --no-build --verbosity normal --filter "FullyQualifiedName!~.IntegrationTests" -- xunit.parallelizeAssembly=true

    - name: Upload coverage # 2. Upload code coverage
      uses: codecov/codecov-action@v2.1.0 # @v3.1.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # 3. Secret usage https://docs.github.com/en/actions/learn-github-actions/contexts
        files: ./src/**/Coverage.xml # https://github.com/codecov/codecov-action/issues/830
